In [80]:
import pandas as pd

In [81]:
import numpy as np

In [82]:
from sklearn.ensemble import RandomForestClassifier

In [83]:
from sklearn.linear_model import LogisticRegression

In [84]:
import os

os.listdir()

['.config',
 'vle.csv',
 'student.txt',
 'student-por.csv',
 'student-mat.csv',
 'student-merge.R',
 'student.zip',
 'studentRegistration.csv',
 'studentAssessment.csv',
 'courses.csv',
 'studentVle.csv',
 'assessments.csv',
 'studentInfo.csv',
 'sample_data']

In [85]:
import os

os.listdir()

['.config',
 'vle.csv',
 'student.txt',
 'student-por.csv',
 'student-mat.csv',
 'student-merge.R',
 'student.zip',
 'studentRegistration.csv',
 'studentAssessment.csv',
 'courses.csv',
 'studentVle.csv',
 'assessments.csv',
 'studentInfo.csv',
 'sample_data']

In [86]:
import pandas as pd

In [87]:
# Loading UCI Student Performance Dataset
uci = pd.read_csv("student-mat.csv", sep=";")

In [88]:
# Loading OULAD Dataset
oulad = pd.read_csv("studentInfo.csv")

In [89]:
uci.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,6,5,6,6
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,4,5,5,6
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,10,7,8,10
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,2,15,14,15
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,4,6,10,10

In [90]:
oulad.head()

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass

In [91]:
uci.shape

(395, 33)

In [92]:
uci.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 395 entries, 0 to 394
Data columns (total 33 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   school      395 non-null    object
 1   sex         395 non-null    object
 2   age         395 non-null    int64
 3   address     395 non-null    object
 4   famsize     395 non-null    object
 5   Pstatus     395 non-null    object
 6   Medu        395 non-null    int64
 7   Fedu        395 non-null    int64
 8   Mjob        395 non-null    object
 9   Fjob        395 non-null    object
 10  reason      395 non-null    object
 11  guardian    395 non-null    object
 12  traveltime  395 non-null    int64
 13  studytime   395 non-null    int64
 14  failures    395 non-null    int64
 15  schoolsup   395 non-null    object
 16  famsup      395 non-null    object
 17  paid        395 non-null    object
 18  activities  395 non-null    object
 19  nursery     395 non-null    object
 20  higher      395 non-null    object
 21  internet    395 non-null    object
 22  romantic    395 non-null    object
 23  famrel      395 non-null    int64
 24  freetime    395 non-null    int64
 25  goout       395 non-null    int64
 26  Dalc        395 non-null    int64
 27  Walc        395 non-null    int64
 28  health      395 non-null    int64
 29  absences    395 non-null    int64
 30  G1          395 non-null    int64
 31  G2          395 non-null    int64
 32  G3          395 non-null    int64
dtypes: int64(16), object(17)
memory usage: 102.0+ KB

In [93]:
oulad.shape

(32593, 12)

In [94]:
oulad.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32593 entries, 0 to 32592
Data columns (total 12 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   code_module           32593 non-null  object
 1   code_presentation     32593 non-null  object
 2   id_student            32593 non-null  int64
 3   gender                32593 non-null  object
 4   region                32593 non-null  object
 5   highest_education     32593 non-null  object
 6   imd_band              31482 non-null  object
 7   age_band              32593 non-null  object
 8   num_of_prev_attempts  32593 non-null  int64
 9   studied_credits       32593 non-null  int64
 10  disability            32593 non-null  object
 11  final_result          32593 non-null  object
dtypes: int64(3), object(9)
memory usage: 3.0+ MB

In [95]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

In [96]:
uci_ml = uci.copy()

In [97]:
# Creating binary target
uci_ml["pass"] = (uci_ml["G3"] >= 10).astype(int)

In [98]:
# Removing original grades
uci_ml = uci_ml.drop(["G1", "G2", "G3"], axis=1)

In [99]:
uci_ml.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,internet,romantic,famrel,freetime,goout,Dalc,Walc,health,absences,pass
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,no,no,4,3,4,1,1,3,6,0
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,yes,no,5,3,3,1,1,3,4,0
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,yes,no,4,3,2,2,3,3,10,1
3,GP,F,15,U,GT3,T,4,2,health,services,...,yes,yes,3,2,2,1,1,5,2,1
4,GP,F,16,U,GT3,T,3,3,other,other,...,no,no,4,3,2,1,2,5,4,1

In [100]:
uci_ml.shape

(395, 31)

In [101]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

In [102]:
# Separating features and target
X_uci = uci_ml.drop("pass", axis=1)
y_uci = uci_ml["pass"]

In [103]:
# Finding categorical columns
categorical_cols = X_uci.select_dtypes(include="object").columns

In [104]:
# Finding numerical columns
numerical_cols = X_uci.select_dtypes(exclude="object").columns

In [105]:
# Encode categorical variables
preprocessor = ColumnTransformer(
    transformers=[
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_cols)
    ],
    remainder="passthrough"
)

X_uci_encoded = preprocessor.fit_transform(X_uci)

In [106]:
X_uci_encoded.shape

(395, 56)

In [107]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X_uci_encoded,
    y_uci,
    test_size=0.2,
    random_state=42,
    stratify=y_uci
)

In [108]:
X_uci_encoded.shape

(395, 56)

In [109]:
#Splitting the UCI data into training and testing sets
from sklearn.model_selection import train_test_split

X_train_uci, X_test_uci, y_train_uci, y_test_uci = train_test_split(
    X_uci_encoded,
    y_uci,
    test_size=0.2,
    random_state=42,
    stratify=y_uci
)

In [110]:
print(X_train_uci.shape)
print(X_test_uci.shape)

(316, 56)
(79, 56)

In [111]:
from sklearn.ensemble import RandomForestClassifier

rf_uci = RandomForestClassifier(
    random_state=42
)

rf_uci.fit(X_train_uci, y_train_uci)

RandomForestClassifier(random_state=42)

In [112]:
#Making predictions with Random Forest
rf_predictions = rf_uci.predict(X_test_uci)

In [113]:
from sklearn.metrics import accuracy_score, classification_report

print("Random Forest Accuracy:")
print(accuracy_score(y_test_uci, rf_predictions))

print("\nClassification Report:")
print(classification_report(y_test_uci, rf_predictions))

Random Forest Accuracy:
0.6329113924050633

Classification Report:
              precision    recall  f1-score   support

           0       0.36      0.15      0.22        26
           1       0.68      0.87      0.76        53

    accuracy                           0.63        79
   macro avg       0.52      0.51      0.49        79
weighted avg       0.57      0.63      0.58        79

In [114]:
#Logitic Regression
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler(with_mean=False)

X_train_scaled = scaler.fit_transform(X_train_uci)
X_test_scaled = scaler.transform(X_test_uci)

In [115]:
from sklearn.linear_model import LogisticRegression

lr_uci = LogisticRegression(
    random_state=42,
    max_iter=1000
)

lr_uci.fit(X_train_scaled, y_train_uci)

LogisticRegression(max_iter=1000, random_state=42)

In [116]:
lr_predictions = lr_uci.predict(X_test_scaled)

In [117]:
print("Logistic Regression Accuracy:")
print(accuracy_score(y_test_uci, lr_predictions))

print("\nClassification Report:")
print(classification_report(y_test_uci, lr_predictions))

Logistic Regression Accuracy:
0.6329113924050633

Classification Report:
              precision    recall  f1-score   support

           0       0.43      0.35      0.38        26
           1       0.71      0.77      0.74        53

    accuracy                           0.63        79
   macro avg       0.57      0.56      0.56        79
weighted avg       0.62      0.63      0.62        79

In [118]:
import os
os.listdir()

['.config',
 'vle.csv',
 'student.txt',
 'student-por.csv',
 'student-mat.csv',
 'student-merge.R',
 'student.zip',
 'studentRegistration.csv',
 'studentAssessment.csv',
 'courses.csv',
 'studentVle.csv',
 'assessments.csv',
 'studentInfo.csv',
 'sample_data']

In [119]:
import pandas as pd

oulad = pd.read_csv("studentInfo.csv")

print(oulad.shape)
oulad.head()

(32593, 12)

,code_module,code_presentation,id_student,gender,region,highest_education,imd_band,age_band,num_of_prev_attempts,studied_credits,disability,final_result
0,AAA,2013J,11391,M,East Anglian Region,HE Qualification,90-100%,55<=,0,240,N,Pass
1,AAA,2013J,28400,F,Scotland,HE Qualification,20-30%,35-55,0,60,N,Pass
2,AAA,2013J,30268,F,North Western Region,A Level or Equivalent,30-40%,35-55,0,60,Y,Withdrawn
3,AAA,2013J,31604,F,South East Region,A Level or Equivalent,50-60%,35-55,0,60,N,Pass
4,AAA,2013J,32885,F,West Midlands Region,Lower Than A Level,50-60%,0-35,0,60,N,Pass

In [120]:
oulad_ml = oulad.copy()

oulad_ml["success"] = oulad_ml["final_result"].apply(
    lambda x: 1 if x in ["Pass", "Distinction"] else 0
)

oulad_ml = oulad_ml.drop(
    ["id_student", "final_result"],
    axis=1
)

In [121]:
oulad_ml["success"].value_counts()

success
0    17208
1    15385
Name: count, dtype: int64

In [122]:
oulad_features = oulad_ml.drop("success", axis=1)

oulad_encoded = pd.get_dummies(
    oulad_features,
    drop_first=True
)

print(oulad_encoded.shape)

(32593, 40)

In [123]:
oulad_encoded.head()

,num_of_prev_attempts,studied_credits,code_module_BBB,code_module_CCC,code_module_DDD,code_module_EEE,code_module_FFF,code_module_GGG,code_presentation_2013J,code_presentation_2014B,...,imd_band_30-40%,imd_band_40-50%,imd_band_50-60%,imd_band_60-70%,imd_band_70-80%,imd_band_80-90%,imd_band_90-100%,age_band_35-55,age_band_55<=,disability_Y
0,0,240,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
1,0,60,False,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,True,False,False
2,0,60,False,False,False,False,False,False,True,False,...,True,False,False,False,False,False,False,True,False,True
3,0,60,False,False,False,False,False,False,True,False,...,False,False,True,False,False,False,False,True,False,False
4,0,60,False,False,False,False,False,False,True,False,...,False,False,True,False,False,False,False,False,False,False

In [124]:
print(oulad_encoded.isnull().sum().sum())

0

In [125]:
print(oulad_encoded.shape)

(32593, 40)

In [126]:
from sklearn.model_selection import train_test_split

X_train_oulad, X_test_oulad, y_train_oulad, y_test_oulad = train_test_split(
    oulad_encoded,
    oulad_ml["success"],
    test_size=0.2,
    random_state=42,
    stratify=oulad_ml["success"]
)

print(X_train_oulad.shape)
print(X_test_oulad.shape)

(26074, 40)
(6519, 40)

In [56]:
from sklearn.ensemble import RandomForestClassifier

rf_oulad = RandomForestClassifier(
    random_state=42
)

rf_oulad.fit(X_train_oulad, y_train_oulad)

RandomForestClassifier(random_state=42)

In [57]:
rf_oulad_predictions = rf_oulad.predict(X_test_oulad)

In [58]:
from sklearn.metrics import accuracy_score, classification_report

print("OULAD Random Forest Accuracy:")
print(accuracy_score(y_test_oulad, rf_oulad_predictions))

print("\nClassification Report:")
print(classification_report(y_test_oulad, rf_oulad_predictions))

OULAD Random Forest Accuracy:
0.5924221506366008

Classification Report:
              precision    recall  f1-score   support

           0       0.61      0.64      0.62      3442
           1       0.57      0.54      0.56      3077

    accuracy                           0.59      6519
   macro avg       0.59      0.59      0.59      6519
weighted avg       0.59      0.59      0.59      6519

In [59]:
from sklearn.preprocessing import StandardScaler

scaler_oulad = StandardScaler(with_mean=False)

X_train_oulad_scaled = scaler_oulad.fit_transform(X_train_oulad)
X_test_oulad_scaled = scaler_oulad.transform(X_test_oulad)

In [60]:
from sklearn.linear_model import LogisticRegression

lr_oulad = LogisticRegression(
    random_state=42,
    max_iter=1000
)

lr_oulad.fit(X_train_oulad_scaled, y_train_oulad)

LogisticRegression(max_iter=1000, random_state=42)

In [61]:
lr_oulad_predictions = lr_oulad.predict(X_test_oulad_scaled)

In [62]:
print("OULAD Logistic Regression Accuracy:")
print(accuracy_score(y_test_oulad, lr_oulad_predictions))

print("\nClassification Report:")
print(classification_report(y_test_oulad, lr_oulad_predictions))

OULAD Logistic Regression Accuracy:
0.6217211228716061

Classification Report:
              precision    recall  f1-score   support

           0       0.63      0.68      0.65      3442
           1       0.61      0.56      0.58      3077

    accuracy                           0.62      6519
   macro avg       0.62      0.62      0.62      6519
weighted avg       0.62      0.62      0.62      6519

In [63]:
import pandas as pd

rf_importance = pd.DataFrame({
    "feature": X_train_oulad.columns,
    "importance": rf_oulad.feature_importances_
})

rf_importance = rf_importance.sort_values(
    "importance",
    ascending=False
)

rf_importance.head(10)

                                 feature  importance
1                        studied_credits    0.111261
11                              gender_M    0.054023
37                        age_band_35-55    0.047303
10               code_presentation_2014J    0.035946
8                code_presentation_2013J    0.032780
0                   num_of_prev_attempts    0.031811
25  highest_education_Lower Than A Level    0.031252
9                code_presentation_2014B    0.029198
30                       imd_band_30-40%    0.027957
39                          disability_Y    0.027186

In [64]:
lr_coefficients = pd.DataFrame({
    "feature": X_train_oulad.columns,
    "coefficient": lr_oulad.coef_[0]
})

lr_coefficients["absolute_coefficient"] = (
    lr_coefficients["coefficient"].abs()
)

lr_coefficients = lr_coefficients.sort_values(
    "absolute_coefficient",
    ascending=False
)

lr_coefficients.head(10)

                                 feature  coefficient  absolute_coefficient
3                        code_module_CCC    -0.428990              0.428990
4                        code_module_DDD    -0.362866              0.362866
2                        code_module_BBB    -0.289438              0.289438
25  highest_education_Lower Than A Level    -0.289316              0.289316
6                        code_module_FFF    -0.257144              0.257144
1                        studied_credits    -0.243139              0.243139
0                   num_of_prev_attempts    -0.169479              0.169479
5                        code_module_EEE    -0.148145              0.148145
36                      imd_band_90-100%     0.126409              0.126409
35                       imd_band_80-90%     0.105058              0.105058

In [65]:
print(uci.shape)

(395, 33)

In [66]:
uci["pass"] = (uci["G3"] >= 10).astype(int)

X_uci = uci.drop(["G1", "G2", "G3", "pass"], axis=1)
y_uci = uci["pass"]

In [67]:
rf_uci
lr_uci
X_train_uci

array([[ 1.,  0.,  0., ...,  1.,  3.,  0.],
       [ 1.,  0.,  0., ...,  1.,  4.,  6.],
       [ 1.,  0.,  1., ...,  2.,  4.,  0.],
       ...,
       [ 1.,  0.,  0., ...,  5.,  5.,  4.],
       [ 1.,  0.,  1., ...,  1.,  4., 14.],
       [ 0.,  1.,  0., ...,  3.,  2.,  8.]])

In [68]:
print(X_uci_encoded.shape)

(395, 56)

In [69]:
[name for name in globals() if "uci" in name.lower()]

['uci',
 'uci_ml',
 'X_uci',
 'y_uci',
 'X_uci_encoded',
 'X_train_uci',
 'X_test_uci',
 'y_train_uci',
 'y_test_uci',
 'rf_uci',
 'lr_uci']

In [70]:
uci_feature_names = pd.get_dummies(
    X_uci,
    drop_first=True
).columns

print(len(uci_feature_names))

39

In [71]:
print("X_uci:", X_uci.shape)
print("X_uci_encoded:", X_uci_encoded.shape)
print("RF features:", len(rf_uci.feature_importances_))

X_uci: (395, 30)
X_uci_encoded: (395, 56)
RF features: 56

In [72]:
uci_encoded_df = pd.get_dummies(
    X_uci,
    drop_first=True
)

print(uci_encoded_df.shape)

(395, 39)

In [73]:
uci_ml = uci.copy()

uci_ml["pass"] = (uci_ml["G3"] >= 10).astype(int)

X_uci = uci_ml.drop(
    ["G1", "G2", "G3", "pass"],
    axis=1
)

y_uci = uci_ml["pass"]

In [74]:
X_uci_encoded = pd.get_dummies(
    X_uci,
    drop_first=True
)

print(X_uci_encoded.shape)

(395, 39)

In [75]:
X_train_uci, X_test_uci, y_train_uci, y_test_uci = train_test_split(
    X_uci_encoded,
    y_uci,
    test_size=0.2,
    random_state=42,
    stratify=y_uci
)

In [76]:
rf_uci = RandomForestClassifier(
    random_state=42
)

rf_uci.fit(X_train_uci, y_train_uci)

RandomForestClassifier(random_state=42)

In [77]:
scaler_uci = StandardScaler(with_mean=False)

X_train_uci_scaled = scaler_uci.fit_transform(X_train_uci)
X_test_uci_scaled = scaler_uci.transform(X_test_uci)

lr_uci = LogisticRegression(
    random_state=42,
    max_iter=1000
)

lr_uci.fit(X_train_uci_scaled, y_train_uci)

LogisticRegression(max_iter=1000, random_state=42)

In [78]:
uci_rf_importance = pd.DataFrame({
    "feature": X_train_uci.columns,
    "importance": rf_uci.feature_importances_
}).sort_values(
    "importance",
    ascending=False
)

uci_rf_importance.head(10)

     feature  importance
5   failures    0.094421
12  absences    0.093302
8      goout    0.056362
0        age    0.049519
11    health    0.046366
7   freetime    0.043550
10      Walc    0.042060
2       Fedu    0.041583
1       Medu    0.037975
6     famrel    0.033760

In [79]:
uci_lr_coefficients = pd.DataFrame({
    "feature": X_train_uci.columns,
    "coefficient": lr_uci.coef_[0]
})

uci_lr_coefficients["absolute_coefficient"] = (
    uci_lr_coefficients["coefficient"].abs()
)

uci_lr_coefficients = uci_lr_coefficients.sort_values(
    "absolute_coefficient",
    ascending=False
)

uci_lr_coefficients.head(10)

            feature  coefficient  absolute_coefficient
5          failures    -0.978956              0.978956
8             goout    -0.515525              0.515525
10             Walc     0.485771              0.485771
21     Mjob_teacher    -0.370703              0.370703
31    schoolsup_yes    -0.349623              0.349623
36       higher_yes     0.247745              0.247745
14            sex_M     0.235130              0.235130
35      nursery_yes    -0.232879              0.232879
18      Mjob_health     0.230930              0.230930
29  guardian_mother    -0.225679              0.225679